name: Batch Download and Release Videos

on:
  workflow_dispatch:
    inputs:
      urls:
        description: '请填写docker镜像名称,多个用英文逗号分开'
        required: true
  push:
    branches:
      - main  # 触发工作流的分支，可以根据需要更改

jobs:
  build:
    runs-on: ubuntu-latest  # 运行工作流的虚拟环境

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg zip
    - name: Create videos directory
      run: |
        pwd
        sudo mkdir -p /videos
        
    - name: Batch download videos
      run: |
        VIDEO_URLS="${{ github.event.inputs.urls }}"
        index=1;
        for url in $VIDEO_URLS; do
          sudo ffmpeg -threads 3 -i "$url"  -c copy  /videos/$index.mp4
          ((index++))
        done

    - name: Create zip file
      run: |
        cd /
        sudo  zip -P 10241042 -r videos.zip /videos/* # 假设所有视频都是 mp4 格式

    - name: Create release
      id: create_release
      uses: softprops/action-gh-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: DockerTarBuilder-AMD64
        release_name: ${{ env.RELEASE_NAME }} for x86-64
        draft: false
        prerelease: false

    - name: Upload zip to release
      uses: softprops/action-gh-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: DockerTarBuilder-AMD64
        files: /videos.zip
        token: ${{ secrets.GITHUB_TOKEN }}
          
